version: '3'
networks:
  back-end:

services:
  back:
    build:
      context: .
    command: mvn spring-boot:run
    volumes:
      - '.:/back-end'
    working_dir: /back-end
    networks:
      - back-end
    ports:
      - 8081:8080
